include:
    - project: 'unreal-marketplace/pluginsdevops'
      ref: Live
      file: 
        - 'plugin-ci.yml'
        - 'plugin-cd.yml'

stages:
  - prepare
  - build
  - package

prepare:
  extends: .prepare-job

build:
  extends: .build-job

package:
  extends: .package-job
