stages:
  - build
  - deploy

build-job:
  stage: build
  trigger:
    include:
    - project: 'unreal-marketplace/pluginsdevops'
      ref: Live
      file: 
        - 'plugin-ci.yml'
    strategy: depend

deploy-job:
  stage: deploy
  only:
    refs:
      - Live
  trigger:
    include:
    - project: 'unreal-marketplace/pluginsdevops'
      ref: Live
      file: 
        - 'plugin-cd.yml'
    strategy: depend
