stages:
  - prepare
  - build
  - package

include:
    - project: 'unreal-marketplace/pluginsdevops'
      ref: Live
      file: 
        - 'plugin-ci.yml'
        - 'plugin-cd.yml'

prepare:
  stage: prepare
  extends: .prepare-job

build:
  stage: build
  extends: .build-job

package:
  stage: package
  extends: .package-job
