// Copyright Out-of-the-Box Plugins 2018-2020. All Rights Reserved.

#include "K2Node_InvokeEventPayload.h"

#include "K2Node_CallFunction.h"	// for UK2Node_CallFunction
#include "Kismet/GameplayStatics.h" // for UGameplayStatics
#include "KismetCompiler.h"			// for FKismetCompilerContext 

#include "ESPayload.h" // for UESPayload

#define LOCTEXT_NAMESPACE "EventsSystemEditor"

namespace FPinNames
{
	FName GetEventPinNameText() { return FName(TEXT("EventToInvoke")); }
}

UK2Node_InvokeEventPayload::UK2Node_InvokeEventPayload(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	NodeTooltip = LOCTEXT("InvokeEventPayloadNodeTooltip", "Invoke an event with an optional payload creation.");
}

//////////////////////////////////////////////////////////////////////////
// UK2Node_ConstructObjectFromClass interface
bool UK2Node_InvokeEventPayload::IsSpawnVarPin(UEdGraphPin* Pin) const
{
	bool EventPinCheck = (Pin->PinName != FPinNames::GetEventPinNameText());
	return EventPinCheck && Super::IsSpawnVarPin(Pin);
}

FText UK2Node_InvokeEventPayload::GetBaseNodeTitle() const
{
	return LOCTEXT("InvokeEventPayload_BaseTitle", "Invoke ESEvent with Payload");
}

FText UK2Node_InvokeEventPayload::GetNodeTitleFormat() const
{
	return LOCTEXT("InvokeEventPayload", "Invoke ESEvent with {ClassName} Payload");
}

UClass* UK2Node_InvokeEventPayload::GetClassPinBaseClass() const
{
	return UESPayload::StaticClass();
}

//////////////////////////////////////////////////////////////////////////
// UEdGraphNode interface
void UK2Node_InvokeEventPayload::AllocateDefaultPins()
{
	Super::AllocateDefaultPins();
	
	FCreatePinParams PinParams;
	PinParams.Index = 1; // Place the event pin right after the flow node.

	UEdGraphPin* InEventPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UESEvent::StaticClass(), FPinNames::GetEventPinNameText(), PinParams);

	UEdGraphPin* ClassPin = GetClassPin();
	ClassPin->bAdvancedView = true;

	if (ENodeAdvancedPins::NoPins == AdvancedPinDisplay)
	{
		AdvancedPinDisplay = ENodeAdvancedPins::Hidden;
	}
}

void UK2Node_InvokeEventPayload::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	if (Pin == GetClassPin())
	{
		ResetClassPinToAutoGenerated();
	}

	Super::PinDefaultValueChanged(Pin);
}

void UK2Node_InvokeEventPayload::PinConnectionListChanged(UEdGraphPin* Pin)
{
	if (Pin == GetClassPin())
	{
		ResetClassPinToAutoGenerated();
	}

	Super::PinConnectionListChanged(Pin);
}

FText UK2Node_InvokeEventPayload::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	FText SuperValue = Super::GetNodeTitle(TitleType);
	if (!SuperValue.CompareTo(FText::FromString("Construct NONE")))
	{
		return LOCTEXT("InvokeEventPayloadK2Node_NoPayload", "Invoke ESEvent without payload");
	}
	else
	{
		return SuperValue;
	}
}

void UK2Node_InvokeEventPayload::ExpandNode(class FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	UK2Node_CallFunction* CallCreateNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	CallCreateNode->FunctionReference.SetExternalMember(GET_FUNCTION_NAME_CHECKED(UGameplayStatics, SpawnObject), UGameplayStatics::StaticClass());
	CallCreateNode->AllocateDefaultPins();

	UK2Node_CallFunction* CallInvokeNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	CallInvokeNode->FunctionReference.SetExternalMember(GET_FUNCTION_NAME_CHECKED(UESEvent, Invoke), UESEvent::StaticClass());
	CallInvokeNode->AllocateDefaultPins();

	bool bSucceeded = true;
	UClass* ClassToSpawn = GetClassToSpawn();

	//connect exe
	{
		UEdGraphPin* SpawnExecPin = GetExecPin();
		UEdGraphPin* CallExecPin = CallCreateNode->GetExecPin();
		bSucceeded &= SpawnExecPin && CallExecPin && CompilerContext.MovePinLinksToIntermediate(*SpawnExecPin, *CallExecPin).CanSafeConnect();
	}

	// Move 'then' connection from spawn node to 'finish spawn'
	CompilerContext.MovePinLinksToIntermediate(*GetThenPin(), *CallInvokeNode->GetThenPin());

	//connect class
	{
		UEdGraphPin* SpawnClassPin = GetClassPin();
		UEdGraphPin* CallClassPin = CallCreateNode->FindPin(TEXT("ObjectClass"));
		bSucceeded &= SpawnClassPin && CallClassPin && CompilerContext.MovePinLinksToIntermediate(*SpawnClassPin, *CallClassPin).CanSafeConnect();
	}

	//connect outer
	{
		UEdGraphPin* SpawnOuterPin = GetEventPin();
		UEdGraphPin* CallOuterPin = CallCreateNode->FindPin(TEXT("Outer"));
		bSucceeded &= SpawnOuterPin && CallOuterPin && CompilerContext.CopyPinLinksToIntermediate(*SpawnOuterPin, *CallOuterPin).CanSafeConnect();
	}

	// Connect output actor from 'begin' to 'finish'
	CallCreateNode->GetReturnValuePin()->MakeLinkTo(CallInvokeNode->FindPin(TEXT("payload")));

	// Copy transform connection
	CompilerContext.CopyPinLinksToIntermediate(*GetEventPin(), *CallInvokeNode->FindPin(TEXT("eventToInvoke")));

	CallCreateNode->GetReturnValuePin()->PinType = GetResultPin()->PinType; // Copy type so it uses the right actor subclass
	CompilerContext.MovePinLinksToIntermediate(*GetResultPin(), *CallCreateNode->GetReturnValuePin());

	UEdGraphPin* LastThen = FKismetCompilerUtilities::GenerateAssignmentNodes(CompilerContext, SourceGraph, CallCreateNode, this, CallCreateNode->GetReturnValuePin(), ClassToSpawn);

	// Make exec connection between 'then' on last node and 'finish'
	LastThen->MakeLinkTo(CallInvokeNode->GetExecPin());

	BreakAllNodeLinks();

	if (!bSucceeded)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("InvokeEventPayloadK2Node_Error", "Invoke ES Event Error @@").ToString(), this);
	}
	else
	{
		UEdGraphPin* SpawnOuterPin = GetEventPin();
		if (SpawnOuterPin && SpawnOuterPin)
		{
			bool bHasValue = SpawnOuterPin->DefaultObject != NULL || SpawnOuterPin->HasAnyConnections();

			if (!bHasValue)
			{
				CompilerContext.MessageLog.Warning(*LOCTEXT("InvokeEventPayloadK2Node_Warning", "Invoke ES Event has no event.").ToString(), this);
			}
		}
	}
}

bool UK2Node_InvokeEventPayload::CanUserEditPinAdvancedViewFlag() const
{
	return true;
}

//////////////////////////////////////////////////////////////////////////
// UK2Node interface
FText UK2Node_InvokeEventPayload::GetMenuCategory() const
{
	return LOCTEXT("InvokeEventPayloadK2Node_MenuCategory", "EventsSystem");
}

//////////////////////////////////////////////////////////////////////////
// Helpers
UEdGraphPin* UK2Node_InvokeEventPayload::GetEventPin() const
{
	UEdGraphPin* Pin = FindPin(FPinNames::GetEventPinNameText());
	ensure(nullptr == Pin || Pin->Direction == EGPD_Input);
	return Pin;
}

void UK2Node_InvokeEventPayload::ResetClassPinToAutoGenerated()
{
	for (UEdGraphPin* PinIt : Pins)
	{
		if (IsSpawnVarPin(PinIt))
		{
			FString AutoGeneratedValue = PinIt->AutogeneratedDefaultValue;
			PinIt->DefaultValue = AutoGeneratedValue;
		}
	}
}

#undef LOCTEXT_NAMESPACE